const Discord = require("discord.js");

exports.run = (client, message, args) => {
  var Random = [
"**0**",
"**1**",
"**2**",
"**3**",
"**4**",
"**5**",
"**6**",
"**7**",
"**8**",
"**9**",
"**10**",
"**11**",
"**12**",
"**13**",
"**14**",
"**15**",
"**16**",
"**17**",
"**18**",
"**19**",
"**20**",
"**21**",
"**22**",
"**23**",
"**24**",
"**25**",
"**26**",
"**27**",
"**28**",
"**29**",
"**30**",
"**31**",
"**32**",
"**33**",
"**34**",
"**35**",
"**36**",
"**37**",
"**38**",
"**39**",
"**40**",
"**41**",
"**42**",
"**43**",
"**44**",
"**45**",
"**46**",
"**47**",
"**48**",
"**49**",
"**50** :sunglasses: ",
"**51** :sunglasses: ",
"**52** :sunglasses: ",
"**53** :sunglasses: ",
"**54** :sunglasses: ",
"**55** :sunglasses: ",
"**56** :sunglasses: ",
"**57** :sunglasses: ",
"**58** :sunglasses: ",
"**59** :sunglasses: ",
"**60** :sunglasses: ",
"**61** :sunglasses: ",
"**62** :sunglasses: ",
"**63** :sunglasses: ",
"**64** :sunglasses: ",
"**65** :sunglasses: ",
"**66** :sunglasses: ",
"**67** :sunglasses: ",
"**68** :sunglasses: ",
"**69** :sunglasses: ",
"**70** :sunglasses: ",
"**71** :sunglasses: ",
"**72** :sunglasses: ",
"**73** :sunglasses: ",
"**74** :sunglasses: ",
"**75** :sunglasses: ",
"**76** :sunglasses: ",
"**77** :sunglasses: ",
"**78** :sunglasses: ",
"**79** :sunglasses: ",
"**80** :sunglasses: ",
"**81** :sunglasses: ",
"**82** :sunglasses: ",
"**83** :sunglasses: ",
"**84** :sunglasses: ",
"**85** :sunglasses: ",
"**86** :sunglasses: ",
"**87** :sunglasses: ",
"**88** :sunglasses: ",
"**89** :sunglasses: ",
"**90** :sunglasses: ",
"**91** :sunglasses: ",
"**92** :sunglasses: ",
"**93** :sunglasses: ",
"**94** :sunglasses: ",
"**95** :sunglasses: ",
"**96** :sunglasses: ",
"**97** :sunglasses: ",
"**98** :sunglasses: ",
"**99** :sunglasses: ",
"**100** :sunglasses: ",
  ];
  var gayver = Math.floor(Math.random() * Random.length);
  const gay = new Discord.MessageEmbed()
    .setColor("GREEN")
    .setAuthor(`Gay Sayar 2077`, message.author.avatarURL())
    .setTimestamp()
    .setDescription(`${message.author} %${Random[gayver]} Gaysin :rainbow_flag: `)
  message.channel.send(gay).then(message=> message.react("<a:B_Yildiz:825644101985894400>"))
};
exports.conf = {
  enabled: true,
  guildOnly: false,
  aliases: [],
  permLevel: 0
};

exports.help = {
  name: "gay-sayar",
  description: "gaysayar",
  usage: "Gay Sayar 2077"
};
